pipeline{
    agent any

    parameters{
        choice(name: 'action', choices: 'create\ndelete', description:'choose create/delete')
    }
 stages{
    stage("checkouts"){
        when{ expression { params.action =='create'}}
        steps{
            script{
                git branch: 'main', url: 'https://github.com/kavin-bot/Java_app2023.git'
            }
        }
    } 
    stage("Maven: UnitTest"){
        when{ expression { params.action =='create'}}
        steps{
            script{
                sh 'mvn test'
            }
        }
    }
    stage("IntegrationTest:Maven"){
        when{ expression { params.action =='create'}}
        steps{
            script{
                sh 'mvn verify -DskipUnitTests'
            }
        }
    } 
    stage("StaticCodeAnalysis"){
        when{ expression { params.action =='create'}}
        steps{
            script{
                withSonarQubeEnv(credentialsId: 'jenkinsonar'){
                     sh 'mvn clean package sonar:sonar'
                }
                
            }
        }
    } 
    stage("QualityGate"){
        when{ expression { params.action =='create'}}
        steps{
            script{
                waitForQualityGate abortPipeline: false, credentialsId: 'jenkinsonar'
            }
        }
    } 
 }
}