pipeline{
    agent any

    tools {
        // Install the Maven version configured as "M3" and add it to the path.
        maven "JMaven"
        dockerTool "JDocker"
    }

 stages{
    stage("checkouts"){
        steps{
            script{
                sh'mvn -v'
                sh 'docker version'
            }
        }

    }
 }
}